name: CI/CD
run-name: ${{github.actor}} is testing out Github Actions 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-Website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set working directory to ./site
        # working-directory: ./site
        run: |
          ls ${{ github.workspace }}
          cd site

      - name: Setup NodeJS to version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Check directory
        run: ls -la
